# 1) LLM，通过 Ollama 的 OpenAI 兼容接口
---
kind: llm
spec:
  name: qwen3-1_7b
  type: openai
  config:
    model_name: qwen3:1.7b

# 2) ReAct Agent，挂载 Web Search MCP server
---
kind: agent
spec:
  name: react-agent-qwen
  type: react
  config:
    llm: qwen3-1_7b
    max_iterations: 10
    servers:
      - name: google-search

